services:
  - type: web
    name: gemini-integration-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_API_KEY
        sync: false